### ISSUE TITLE
[DataCap Application] <Cloud Era Cloud Monitoring> - <AI Intelligent Recognition>

### ISSUE THREAD

**Issue by Zzbaoo** [MikeH1999/RFfil#41] opened 2024-08-31 14:45 UTC
### Data Owner Name

Bond

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.gdysd.cn/

### Social Media Handle

hpjnba@gmail.com

### Social Media Type

Other

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1kfgr3dpbxyyjuqoyymtia44gt6zw4rlntskz2ny

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Cloud Era Cloud Monitoring Project:
Currently, we are a professional digital upgrade service provider and operator for the retail industry. Our focus is on providing technological upgrades and solutions to address pain points in China's 5.4 trillion yuan physical retail market, offering integrated marketing, transaction, management, and revenue enhancement solutions for convenience stores and branded chain enterprises.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Machine learning models and training data, image and video data, sensor data, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
Samples of the dataset are as follows:
https://pan.baidu.com/s/1NjRFt8JO6GnDtIjLc8GFGA?pwd=587t
https://pan.baidu.com/s/1DZbJQUTpzj-T64MHZ_Mxmw?pwd=az56
https://pan.baidu.com/s/1Mm2R_nIm3tQZ8EFL3Xdtzg?pwd=xfb2
https://pan.baidu.com/s/1Qah8AA24XNWk37aTtdd8aA?pwd=h8p8
https://pan.baidu.com/s/1MOn4gklUjjMUIKmW6VF3Aw?pwd=b79g
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How did you find your storage providers

Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03178077 US
f03178144 SG
f03178150 JP
f03178158 US
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by MikeH1999** [comment] 2024-09-05 01:50
Where are these data from?
Why you want to store these Information monitoring videos?
Information monitoring data are always regarded as private data. Can you provide more materials to prove that these data are authorized to store as public data on the Filecoin network?

**Comment by Zzbaoo** [comment] 2024-09-05 09:26
> Where are these data from? Why you want to store these Information monitoring videos? Information monitoring data are always regarded as private data. Can you provide more materials to prove that these data are authorized to store as public data on the Filecoin network?

1. We are working on an AI intelligent cloud monitoring project. The data comes from a cloud monitoring platform and captures public areas.
2. The purpose of storing the monitoring information is for AI behavior training, such as detecting theft or scanning for buying and selling activities.
3. We have the necessary documentation, including business certification, and all videos have been registered.

**Comment by MikeH1999** [comment] 2024-09-07 15:58
Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?

**Comment by MikeH1999** [comment] 2024-09-07 16:02
Discover that you are applying using the same application details in more than one route
for example
https://github.com/1475Notary/1475-Allocator/issues/17
https://github.com/fidlabs/Enterprise-Data-Pathway/issues/67
https://github.com/cryptowhizzard/Fil-A-2/issues/19
https://github.com/hash889900/HashTeam/issues/12
https://github.com/fidlabs/Open-Data-Pathway/issues/74
https://github.com/Lind111/EF/issues/22


Can you explain?

**Comment by Zzbaoo** [comment] 2024-09-09 12:47
> 发现您在多个路线中使用相同的申请详细信息进行申请 ，例如 [1475Notary/1475-Allocator#17 ](https://github.com/1475Notary/1475-Allocator/issues/17) [fidlabs/Enterprise-Data-Pathway#67 ](https://github.com/fidlabs/Enterprise-Data-Pathway/issues/67) [cryptowhizzard/Fil-A-2#19 ](https://github.com/cryptowhizzard/Fil-A-2/issues/19) [hash889900/HashTeam#12 ](https://github.com/hash889900/HashTeam/issues/12) [fidlabs/Open-Data-Pathway#74 ](https://github.com/fidlabs/Open-Data-Pathway/issues/74) [Lind111/EF#22](https://github.com/Lind111/EF/issues/22)
> 
> 你能解释一下吗？



> Discover that you are applying using the same application details in more than one route for example [1475Notary/1475-Allocator#17](https://github.com/1475Notary/1475-Allocator/issues/17) [fidlabs/Enterprise-Data-Pathway#67](https://github.com/fidlabs/Enterprise-Data-Pathway/issues/67) [cryptowhizzard/Fil-A-2#19](https://github.com/cryptowhizzard/Fil-A-2/issues/19) [hash889900/HashTeam#12](https://github.com/hash889900/HashTeam/issues/12) [fidlabs/Open-Data-Pathway#74](https://github.com/fidlabs/Open-Data-Pathway/issues/74) [Lind111/EF#22](https://github.com/Lind111/EF/issues/22)
> 
> Can you explain?

Thank you for your attention to my applications. I would like to explain the reasons behind submitting similar application details to multiple projects:

1. I did not receive any response or feedback from some of my previous applications. To increase the chances of success, I decided to submit similar applications to multiple relevant parties. This approach is not intended to be opportunistic but to ensure that my project has the opportunity to be seen and supported by a broader audience.

2. I understand that the Filecoin community encourages collaboration and support but does not explicitly prohibit applying to multiple parties. I have followed the application process for each project and clearly stated my needs and goals in every application. My intention is to find suitable partners for my project, not to gain an unfair advantage through repeated applications.

3. I hope to showcase my project to more potential collaborators through these applications and receive feedback and suggestions to improve my project’s plan and execution. If my approach violates any unwritten norms or expectations of the community, please let me know. I am willing to adjust my application strategy and engage in constructive dialogue.

Thank you very much for your understanding and support!

**Comment by Zzbaoo** [comment] 2024-09-09 13:01
> 相关文件



> Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?



> Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?



> Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?



> Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?

I have sent the relevant documents to your email.

**Comment by Zzbaoo** [comment] 2024-09-09 13:01
> Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?

I have sent the relevant documents to your email.

**Comment by Zzbaoo** [comment] 2024-09-09 13:02
> Discover that you are applying using the same application details in more than one route for example [1475Notary/1475-Allocator#17](https://github.com/1475Notary/1475-Allocator/issues/17) [fidlabs/Enterprise-Data-Pathway#67](https://github.com/fidlabs/Enterprise-Data-Pathway/issues/67) [cryptowhizzard/Fil-A-2#19](https://github.com/cryptowhizzard/Fil-A-2/issues/19) [hash889900/HashTeam#12](https://github.com/hash889900/HashTeam/issues/12) [fidlabs/Open-Data-Pathway#74](https://github.com/fidlabs/Open-Data-Pathway/issues/74) [Lind111/EF#22](https://github.com/Lind111/EF/issues/22)
> 
> Can you explain?

Thank you for your attention to my applications. I would like to explain the reasons behind submitting similar application details to multiple projects:

1. I did not receive any response or feedback from some of my previous applications. To increase the chances of success, I decided to submit similar applications to multiple relevant parties. This approach is not intended to be opportunistic but to ensure that my project has the opportunity to be seen and supported by a broader audience.

2. I understand that the Filecoin community encourages collaboration and support but does not explicitly prohibit applying to multiple parties. I have followed the application process for each project and clearly stated my needs and goals in every application. My intention is to find suitable partners for my project, not to gain an unfair advantage through repeated applications.

3. I hope to showcase my project to more potential collaborators through these applications and receive feedback and suggestions to improve my project’s plan and execution. If my approach violates any unwritten norms or expectations of the community, please let me know. I am willing to adjust my application strategy and engage in constructive dialogue.

Thank you very much for your understanding and support!

**Comment by MikeH1999** [comment] 2024-09-11 06:32
> > Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?
> 
> I have sent the relevant documents to your email.

Only the business license was received
Can you provide more materials to prove that these data are authorized to store as public data on the Filecoin network?

**Comment by MikeH1999** [comment] 2024-09-11 06:33
> > Discover that you are applying using the same application details in more than one route for example [1475Notary/1475-Allocator#17](https://github.com/1475Notary/1475-Allocator/issues/17) [fidlabs/Enterprise-Data-Pathway#67](https://github.com/fidlabs/Enterprise-Data-Pathway/issues/67) [cryptowhizzard/Fil-A-2#19](https://github.com/cryptowhizzard/Fil-A-2/issues/19) [hash889900/HashTeam#12](https://github.com/hash889900/HashTeam/issues/12) [fidlabs/Open-Data-Pathway#74](https://github.com/fidlabs/Open-Data-Pathway/issues/74) [Lind111/EF#22](https://github.com/Lind111/EF/issues/22)
> > Can you explain?
> 
> Thank you for your attention to my applications. I would like to explain the reasons behind submitting similar application details to multiple projects:
> 
> 1. I did not receive any response or feedback from some of my previous applications. To increase the chances of success, I decided to submit similar applications to multiple relevant parties. This approach is not intended to be opportunistic but to ensure that my project has the opportunity to be seen and supported by a broader audience.
> 2. I understand that the Filecoin community encourages collaboration and support but does not explicitly prohibit applying to multiple parties. I have followed the application process for each project and clearly stated my needs and goals in every application. My intention is to find suitable partners for my project, not to gain an unfair advantage through repeated applications.
> 3. I hope to showcase my project to more potential collaborators through these applications and receive feedback and suggestions to improve my project’s plan and execution. If my approach violates any unwritten norms or expectations of the community, please let me know. I am willing to adjust my application strategy and engage in constructive dialogue.
> 
> Thank you very much for your understanding and support!

I'll bring this up at the next meeting.

**Comment by Zzbaoo** [comment] 2024-09-11 14:23
> > > Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?
> > 
> > 
> > I have sent the relevant documents to your email.
> 
> Only the business license was received Can you provide more materials to prove that these data are authorized to store as public data on the Filecoin network?

I have sent an authorization letter to your mailbox. Please check it.

**Comment by MikeH1999** [comment] 2024-09-12 01:53
I would to confirm whether you still want to apply for storing these data as open dataset.

**Comment by MikeH1999** [comment] 2024-09-12 02:00
> > > > Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?
> > > 
> > > 
> > > I have sent the relevant documents to your email.
> > 
> > 
> > Only the business license was received Can you provide more materials to prove that these data are authorized to store as public data on the Filecoin network?
> 
> I have sent an authorization letter to your mailbox. Please check it.

![image](https://github.com/user-attachments/assets/e1d94e74-f336-4d0e-97bd-64c24869a2d5)
![image](https://github.com/user-attachments/assets/dd8958b9-79b9-492c-9316-218498ed4514)

Authorization and business license are confirmed

**Comment by MikeH1999** [comment] 2024-09-12 02:01
> > > > Can you send the relevant documents to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com) for review using your company's domain email address?
> > > 
> > > 
> > > I have sent the relevant documents to your email.
> > 
> > 
> > Only the business license was received Can you provide more materials to prove that these data are authorized to store as public data on the Filecoin network?
> 
> I have sent an authorization letter to your mailbox. Please check it.

![image](https://github.com/user-attachments/assets/e1d94e74-f336-4d0e-97bd-64c24869a2d5)
![image](https://github.com/user-attachments/assets/dd8958b9-79b9-492c-9316-218498ed4514)

Authorization and business license are confirmed

**Comment by MikeH1999** [comment] 2024-09-12 02:09
f03178077 US    Multiaddrs:	/ip4/47.236.144.226/tcp/58419   
![image](https://github.com/user-attachments/assets/064e12d2-3aee-43cd-9d73-286803cc484a)

f03178144 SG   new   Unannounced ip
f03178150 JP    new   Unannounced ip
f03178158 US   new   Unannounced ip


The actual ip does not match the disclosure, can you explain?

**Comment by Zzbaoo** [comment] 2024-09-12 06:47
> f03178077 US Multiaddrs: /ip4/47.236.144.226/tcp/58419 ![image](https://private-user-images.githubusercontent.com/149572051/366694560-064e12d2-3aee-43cd-9d73-286803cc484a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDk2OTEsIm5iZiI6MTcyNjEwOTM5MSwicGF0aCI6Ii8xNDk1NzIwNTEvMzY2Njk0NTYwLTA2NGUxMmQyLTNhZWUtNDNjZC05ZDczLTI4NjgwM2NjNDg0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwMjQ5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGY2MTc3ZmZlNzQ2MmMxYmZjM2EyMmJhMGY2ZDY5YWMxNzQ3Y2U0NDZjZTliZDk2YjI2ZGM2YmYxZGMxODNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QkIhauK4RsbCZWFl1ISnTJ9gWLUIoDRirUFnHetmtWM)
> 
> f03178144 SG new Unannounced ip f03178150 JP new Unannounced ip f03178158 US new Unannounced ip
> 
> The actual ip does not match the disclosure, can you explain?

At the time of applying for DataCap, the actual deployment plan of these storage nodes has not yet been finalized. The geographical location of the nodes may be adjusted according to actual needs and resource allocation, so it may be different from the location provided when initially applying. I would like to add a few more storage nodes f03179555 (Singapore) f03179570 (Singapore) f03178077 (Tokyo, Japan) f03178144 (Tokyo, Japan)

**Comment by Zzbaoo** [comment] 2024-09-12 07:34
> I would to confirm whether you still want to apply for storing these data as open dataset.

Yes, I am sure

**Comment by MikeH1999** [comment] 2024-09-14 07:14
Please update the SP list again to the  form
![image](https://github.com/user-attachments/assets/36269141-81ec-451c-b7e5-4b2fe65618a6)

I see that all the SPs are not in China, and send the supporting documents of the geographic location information of all the SPs to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com)

**Comment by Zzbaoo** [comment] 2024-09-14 07:45
> Please update the SP list again to the form ![image](https://private-user-images.githubusercontent.com/149572051/367496300-36269141-81ec-451c-b7e5-4b2fe65618a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTk5NjAsIm5iZiI6MTcyNjI5OTY2MCwicGF0aCI6Ii8xNDk1NzIwNTEvMzY3NDk2MzAwLTM2MjY5MTQxLTgxZWMtNDUxYy1iN2U1LTRiMmZlNjU2MThhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQwNzQxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJhMWFhZWRmYjkyNjE3MDhlMTUzNWNmMmZkZjViYmJlY2U2OGNlNmY4NjBjMjlhMjExMTdjYmEyYmU4NzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qz1eFMW1DQipjM2XG9IPn1BK3BpZEqSvWVcSEoj1doU)
> 
> I see that all the SPs are not in China, and send the supporting documents of the geographic location information of all the SPs to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com)

It has been sent to your email, please check

**Comment by MikeH1999** [comment] 2024-09-18 06:40
> > Please update the SP list again to the form ![image](https://private-user-images.githubusercontent.com/149572051/367496300-36269141-81ec-451c-b7e5-4b2fe65618a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTk5NjAsIm5iZiI6MTcyNjI5OTY2MCwicGF0aCI6Ii8xNDk1NzIwNTEvMzY3NDk2MzAwLTM2MjY5MTQxLTgxZWMtNDUxYy1iN2U1LTRiMmZlNjU2MThhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQwNzQxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJhMWFhZWRmYjkyNjE3MDhlMTUzNWNmMmZkZjViYmJlY2U2OGNlNmY4NjBjMjlhMjExMTdjYmEyYmU4NzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qz1eFMW1DQipjM2XG9IPn1BK3BpZEqSvWVcSEoj1doU)
> > I see that all the SPs are not in China, and send the supporting documents of the geographic location information of all the SPs to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com)
> 
> It has been sent to your email, please check

What I need is proof of location, like some bills.

**Comment by Zzbaoo** [comment] 2024-09-18 07:43
> > > Please update the SP list again to the form ![image](https://private-user-images.githubusercontent.com/149572051/367496300-36269141-81ec-451c-b7e5-4b2fe65618a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTk5NjAsIm5iZiI6MTcyNjI5OTY2MCwicGF0aCI6Ii8xNDk1NzIwNTEvMzY3NDk2MzAwLTM2MjY5MTQxLTgxZWMtNDUxYy1iN2U1LTRiMmZlNjU2MThhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQwNzQxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJhMWFhZWRmYjkyNjE3MDhlMTUzNWNmMmZkZjViYmJlY2U2OGNlNmY4NjBjMjlhMjExMTdjYmEyYmU4NzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qz1eFMW1DQipjM2XG9IPn1BK3BpZEqSvWVcSEoj1doU)
> > > I see that all the SPs are not in China, and send the supporting documents of the geographic location information of all the SPs to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com)
> > 
> > 
> > It has been sent to your email, please check
> 
> What I need is proof of location, like some bills.

The relevant bill has been sent to your email, please check

**Comment by MikeH1999** [comment] 2024-09-19 01:45
There was also a clear request at the meeting to confirm the SP's physical location information to meet the distributed requirements

**Comment by Zzbaoo** [comment] 2024-10-08 07:22
> From your bill, it looks like you purchased a cloud server, not a physical machine.
> 
> The program does not support VPN, please refer to [question 28](https://github.com/filecoin-project/notary-governance/issues/1054#issuecomment-1890620141)

In question 28 of this link, I saw that VPN is supported, but proof of geographic location is required. I will send the physical machine-related bill to your email address, please check it out.

**Comment by MikeH1999** [comment] 2024-10-09 05:51
f03178077 US
f03178144 SG
f03178150 JP
f03178158 US
Filled out as above

But I only got a bill for China.

**Comment by MikeH1999** [comment] 2024-10-10 04:00
Closing this issue due to non-compliance with some of the rules

Re-applications are welcome once the rules have been met

**Closed by MikeH1999** 2024-10-10 04:00 UTC
Labels: validated, waiting for allocator review
