### ISSUE TITLE
[DataCap Application] <Shenyang Dongya Medical Research Institute Co.> - <East Asia Medical>

### ISSUE THREAD

**Issue by Hunter3576** [MikeH1999/RFfil#6] opened 2024-03-26 03:11 UTC
### Version

1

### DataCap Applicant

Hunter

### Project ID

1

### Data Owner Name

Shenyang Dongya Medical Research Institute Co.

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

http://www.syeamri.com/

### Social Media Handle

hunter_199

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

5

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

1

### Unit for expected size of single dataset

PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1

### Unit for weekly allocation of DataCap requested

PiB

### On-chain address for first allocation

f1wpkzdsyum376fqfg4wgfnhmmcubvqj7duqldpma

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are a company dedicated to providing quality healthcare services. As a leading healthcare provider, we aim to provide our patients with the best possible treatment options through advanced technology and a dedicated team of healthcare professionals. Improving people's quality of life and helping them regain their health and stay well through innovative healthcare solutions. We are committed to being a leader in healthcare, delivering excellence in healthcare and making a positive social impact. We provide comprehensive healthcare services covering a wide range of areas including prevention, diagnosis, treatment and rehabilitation. We have a team of experienced doctors, nurses and healthcare professionals with a wide range of expertise and clinical experience to provide personalised and integrated medical care to our patients.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Medical data, surgical data, equipment and other videos and images, medical literature, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We have our own storage facility . We will use the Boost tool
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1rJvCYROC5m35_GyISvHBXIoRQflhvyzd?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Others

### How did you find your storage providers

Slack, Others

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02519100 GuangZhou
f02215209 Californial
f02770938 HongKong
f02093396 Singapore
f02259777 Singapore
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by MikeH1999** [comment] 2024-03-26 03:24
已收到申请，正在审批

**Comment by MikeH1999** [comment] 2024-03-26 03:31
您能否使用您的官方域名发送电子邮件至1075854961@qq.com 以确认您的身份？

已添加您的微信，请通过一下

**Comment by Hunter3576** [comment] 2024-03-26 03:36
已发送
![企业微信截图_17114241563162](https://github.com/MikeH1999/RFfil/assets/142307066/19c630a8-b024-4104-bffb-7a105bf75373)

**Comment by MikeH1999** [comment] 2024-03-26 03:38
已确认
![image](https://github.com/MikeH1999/RFfil/assets/149572051/a6e2713f-1344-43e0-82ec-90e0a339c28c)

**Comment by MikeH1999** [comment] 2024-03-26 03:59
已通过视频方式确认相关信息
![image](https://github.com/MikeH1999/RFfil/assets/149572051/791ed72d-f0b2-43e4-8355-73c7615171f6)

**Comment by Hunter3576** [comment] 2024-03-26 04:00
感谢

**Comment by MikeH1999** [comment] 2024-03-26 04:03
![image](https://github.com/MikeH1999/RFfil/assets/149572051/3272500e-1633-4f15-aa5d-1f8b8824b3ee)
只有一个SP状态正常，您可以解释一下吗？

**Comment by Hunter3576** [comment] 2024-03-26 04:06
两个全新节点他们技术团队还在陆续准备相关部署环境，新加坡的节点他们还在准备数据，我会持续跟进

**Comment by MikeH1999** [comment] 2024-03-26 04:08
午休时间到了，下午我再确认一遍

**Comment by Hunter3576** [comment] 2024-03-26 05:44
请问还有其他问题吗

**Comment by MikeH1999** [comment] 2024-03-26 06:09
信息通过审查，但是由于机器人的bug还未修复，按照规则第一轮只发放50Tib，要去验证您的数据，所以暂时无法下发额度，预计明天会修复，抱歉

**Comment by MikeH1999** [comment] 2024-03-26 06:26
或者你有历史的申请记录吗，请附上链接

**Comment by Hunter3576** [comment] 2024-03-26 06:27
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2159

**Comment by MikeH1999** [comment] 2024-03-26 06:28
好的，我们团队审核下，迟点给您答复

**Comment by MikeH1999** [comment] 2024-03-28 02:26
@Hunter3576 你好，由于机器人的bug还未修复，暂时不能下发datacap，感谢理解！

**Comment by MikeH1999** [comment] 2024-03-28 08:57
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-03-29 17:12
将发放50Tib的datacap，用于第一轮验证

**Comment by Hunter3576** [comment] 2024-03-29 19:16
好的

**Comment by MikeH1999** [comment] 2024-03-30 05:42
将会取回数据验证

**Comment by MikeH1999** [comment] 2024-03-30 07:22
lotus client  retrieve --miner f02215209 bafybeiea5e6sdw2l367e62jcfd6hl4simuqwhm53us7tn77xign2iqxyem medical
Recv 0 B, Paid 0 FIL, Open (New), 1ms [1709356034782404120|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 5ms [1709356034782404120|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 20ms [1709356034782404120|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 21ms [1709356034782404120|0]
Recv 1.538 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 78ms [1709356034782404120|1575]
Recv 1.864 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 82ms [1709356034782404120|1909]
Recv 51.88 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 128ms [1709356034782404120|53120]
Recv 1.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 345ms [1709356034782404120|1101696]
Recv 2.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2.657s [1709356034782404120|2150272]
Recv 3.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 4.872s [1709356034782404120|3198848]
Recv 4.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 4.99s [1709356034782404120|4247424]
Recv 5.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 7.32s [1709356034782404120|5296000]
Recv 6.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 9.983s [1709356034782404120|6344576]
Recv 7.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 14.571s [1709356034782404120|7393152]
Recv 8.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 16.092s [1709356034782404120|8441728]
Recv 9.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 18.91s [1709356034782404120|9490304]
Recv 10.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 19.028s [1709356034782404120|10538880]
Recv 11.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 21.325s [1709356034782404120|11587456]
Recv 12.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 23.432s [1709356034782404120|12636032]
Recv 13.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 25.758s [1709356034782404120|13684608]
Recv 14.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 28.042s [1709356034782404120|14733184]
Recv 15.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 30.393s [1709356034782404120|15781760]
Recv 16.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 31.984s [1709356034782404120|16830336]
Recv 17.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 34.322s [1709356034782404120|17878912]
Recv 18.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 36.633s [1709356034782404120|18927488]
Recv 19.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 36.795s [1709356034782404120|19976064]
Recv 20.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 39.089s [1709356034782404120|21024640]
Recv 21.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 41.094s [1709356034782404120|22073216]
Recv 22.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 44.255s [1709356034782404120|23121792]
Recv 23.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 46.661s [1709356034782404120|24170368]
Recv 24.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 46.83s [1709356034782404120|25218944]
Recv 25.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 49.113s [1709356034782404120|26267520]
Recv 26.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 51.452s [1709356034782404120|27316096]
Recv 27.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 53.256s [1709356034782404120|28364672]
Recv 28.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 55.655s [1709356034782404120|29413248]
Recv 29.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 57.973s [1709356034782404120|30461824]
Recv 30.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m0.39s [1709356034782404120|31510400]
Recv 31.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m2.711s [1709356034782404120|32558976]
Recv 32.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m4.401s [1709356034782404120|33607552]
Recv 33.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m6.773s [1709356034782404120|34656128]
Recv 34.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m6.896s [1709356034782404120|35704704]
Recv 35.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m11.361s [1709356034782404120|36753280]
Recv 36.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m14.107s [1709356034782404120|37801856]
Recv 37.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m16.722s [1709356034782404120|38850432]

正在取回

**Comment by MikeH1999** [comment] 2024-03-30 08:34
先做个第二轮的分配测试

**Comment by MikeH1999** [comment] 2024-03-31 09:59
> lotus client retrieve --miner f02215209 bafybeiea5e6sdw2l367e62jcfd6hl4simuqwhm53us7tn77xign2iqxyem medical Recv 0 B, Paid 0 FIL, Open (New), 1ms [1709356034782404120|0] Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 5ms [1709356034782404120|0] Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 20ms [1709356034782404120|0] Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 21ms [1709356034782404120|0] Recv 1.538 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 78ms [1709356034782404120|1575] Recv 1.864 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 82ms [1709356034782404120|1909] Recv 51.88 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 128ms [1709356034782404120|53120] Recv 1.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 345ms [1709356034782404120|1101696] Recv 2.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2.657s [1709356034782404120|2150272] Recv 3.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 4.872s [1709356034782404120|3198848] Recv 4.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 4.99s [1709356034782404120|4247424] Recv 5.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 7.32s [1709356034782404120|5296000] Recv 6.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 9.983s [1709356034782404120|6344576] Recv 7.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 14.571s [1709356034782404120|7393152] Recv 8.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 16.092s [1709356034782404120|8441728] Recv 9.051 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 18.91s [1709356034782404120|9490304] Recv 10.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 19.028s [1709356034782404120|10538880] Recv 11.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 21.325s [1709356034782404120|11587456] Recv 12.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 23.432s [1709356034782404120|12636032] Recv 13.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 25.758s [1709356034782404120|13684608] Recv 14.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 28.042s [1709356034782404120|14733184] Recv 15.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 30.393s [1709356034782404120|15781760] Recv 16.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 31.984s [1709356034782404120|16830336] Recv 17.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 34.322s [1709356034782404120|17878912] Recv 18.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 36.633s [1709356034782404120|18927488] Recv 19.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 36.795s [1709356034782404120|19976064] Recv 20.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 39.089s [1709356034782404120|21024640] Recv 21.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 41.094s [1709356034782404120|22073216] Recv 22.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 44.255s [1709356034782404120|23121792] Recv 23.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 46.661s [1709356034782404120|24170368] Recv 24.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 46.83s [1709356034782404120|25218944] Recv 25.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 49.113s [1709356034782404120|26267520] Recv 26.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 51.452s [1709356034782404120|27316096] Recv 27.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 53.256s [1709356034782404120|28364672] Recv 28.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 55.655s [1709356034782404120|29413248] Recv 29.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 57.973s [1709356034782404120|30461824] Recv 30.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m0.39s [1709356034782404120|31510400] Recv 31.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m2.711s [1709356034782404120|32558976] Recv 32.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m4.401s [1709356034782404120|33607552] Recv 33.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m6.773s [1709356034782404120|34656128] Recv 34.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m6.896s [1709356034782404120|35704704] Recv 35.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m11.361s [1709356034782404120|36753280] Recv 36.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m14.107s [1709356034782404120|37801856] Recv 37.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m16.722s [1709356034782404120|38850432]
> 
> 正在取回

取回并抽查了数据样本，与所描述一致，将进行第二轮分配
![image](https://github.com/MikeH1999/RFfil/assets/149572051/09226d93-be8a-4272-a409-14e034acef8c)

**Comment by Hunter3576** [comment] 2024-04-02 06:07
添加一个新的合作伙伴 
f02237006 Singapore

**Comment by Hunter3576** [comment] 2024-04-03 01:23
@MikeH1999 可以分配第三轮datacap了

**Comment by MikeH1999** [comment] 2024-04-03 01:34
![image](https://github.com/MikeH1999/RFfil/assets/149572051/cd206158-6333-4887-92e6-e5592e03643e)
公布的sp信息
f02519100 GuangZhou
f02215209 Californial
f02770938 HongKong
f02093396 Singapore
f02259777 Singapore
f02237006 Singapore

发现f03034045 与所公布的不匹配，您可以解释一下吗？

**Comment by Hunter3576** [comment] 2024-04-03 01:41
@MikeH1999 可能上次遗漏了。再次补充
f03034045  Tokyo

**Comment by MikeH1999** [comment] 2024-04-03 01:46
收到，审查第三轮，数据分配满足分布式要求，单个SP分配未超过30%，将进行第三轮datacap下发

**Comment by Hunter3576** [comment] 2024-04-07 01:05
@MikeH1999 可以分配第四轮datacap了

**Comment by MikeH1999** [comment] 2024-04-07 02:58
![image](https://github.com/MikeH1999/RFfil/assets/149572051/fe861440-58d1-4139-bc48-0df4511f15dc)
收到，审查第四轮，数据分配满足分布式要求，单个SP分配未超过30%，将进行第四轮datacap下发

**Comment by MikeH1999** [comment] 2024-04-16 07:14
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-04-16 13:52
checker:manualTrigger

**Comment by filecoin-watchdog** [comment] 2024-05-09 18:56
checker:manualTrigger

**Comment by filecoin-watchdog** [comment] 2024-05-10 12:06
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-05-14 07:10
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-05-16 02:36
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-05-22 01:25
checker:manualTrigger

**Comment by Hunter3576** [comment] 2024-05-28 01:44
增加新节点
f0872282,f02822222 York    Hong Kong
f01888808 郑建林   罗马尼亚

**Comment by Hunter3576** [comment] 2024-05-28 06:06
再次增加新节点
f01930832  zhao  nanjin
f01390330，f02899169 tiger  xian

**Comment by MikeH1999** [comment] 2024-05-31 07:06
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-06-03 01:16
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-06-03 01:25
> 增加新节点 f0872282,f02822222 York Hong Kong f01888808 郑建林 罗马尼亚

> 再次增加新节点 f01930832 zhao nanjin f01390330，f02899169 tiger xian


这周会检索以上新节点

**Comment by MikeH1999** [comment] 2024-06-04 03:01
![image](https://github.com/MikeH1999/RFfil/assets/149572051/1d47ff82-b377-4ca0-8c13-2328bd5904cc)
![image](https://github.com/MikeH1999/RFfil/assets/149572051/ab6425c6-fd40-47b0-9b1c-31190ce24157)
![image](https://github.com/MikeH1999/RFfil/assets/149572051/f4cbffdd-78d5-415b-b627-8e60676d0667)
As spark is still debugging, manually performed the retrieval test, all normal

**Comment by MikeH1999** [comment] 2024-06-14 01:19
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-06-17 03:13
Wait for the sp to have an Increase in retrieval rate rate in [the spark console](http://filspark.com/dashboard) and start approving the next round of

**Comment by MikeH1999** [comment] 2024-06-21 03:34
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-06-27 01:51
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-02 02:56
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-04 02:04
Any progress so far for Spark support please?

**Comment by MikeH1999** [comment] 2024-07-04 02:05
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-04 02:50
Good to see that two of the SPs supports spark retrieval!

**Comment by Hunter3576** [comment] 2024-07-04 10:38
The following customers have been added again

f02820000 |   |   | GuangZhou
f02639655 |   |   | GuangZhou

**Comment by MikeH1999** [comment] 2024-07-05 01:47
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-05 08:53
checker:manualTrigger

**Comment by Hunter3576** [comment] 2024-07-05 09:09
Already have a sp that supports spark retrieval for the next round of allocation?

**Comment by MikeH1999** [comment] 2024-07-08 03:52
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-08 04:04
Already seeing bot reports moving towards health, can you say a little bit about your plans for data distribution in the later stages?

**Comment by Hunter3576** [comment] 2024-07-08 04:07
At the moment I've been looking for new SPs, prioritizing the allocation of data to new SPs to keep the bot reports healthy, and I've been following up with the spark team

**Comment by MikeH1999** [comment] 2024-07-08 04:11
![image](https://github.com/MikeH1999/RFfil/assets/149572051/54f20e3f-673b-4849-abff-a36fe15d2a1d)
![image](https://github.com/MikeH1999/RFfil/assets/149572051/81c59900-d34f-4e88-8d19-bee073f9b746)

Looking forward to seeing the healthy side of robotics reporting

**Comment by MikeH1999** [comment] 2024-07-16 06:00
checker:manualTrigger

**Comment by Hunter3576** [comment] 2024-07-17 05:58
Addition of two new partners
f02866666 			Tokyo
f03144777			Tokyo

**Comment by MikeH1999** [comment] 2024-07-19 09:41
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-22 01:33
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-22 01:45
> Addition of two new partners f02866666 Tokyo f03144777 Tokyo

请提供这两个SP的地理位置证明至[mike1999_fil@qq.com](mailto:mike1999_fil@qq.com)

**Comment by Hunter3576** [comment] 2024-07-22 01:52
> > Addition of two new partners f02866666 Tokyo f03144777 Tokyo
> 
> Please provide proof of the location of these two SPs to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com)

sent

**Comment by Hunter3576** [comment] 2024-07-22 01:52
Can you trigger the next round now?

**Comment by MikeH1999** [comment] 2024-07-22 01:53
Under review

**Comment by MikeH1999** [comment] 2024-07-22 02:10
> > > Addition of two new partners f02866666 Tokyo f03144777 Tokyo
> > 
> > 
> > Please provide proof of the location of these two SPs to [mike1999_fil@qq.com](mailto:mike1999_fil@qq.com)
> 
> sent

confirmed

**Comment by MikeH1999** [comment] 2024-07-22 02:11
![image](https://github.com/user-attachments/assets/db244f5d-aa42-4575-b7c7-2f53d468cd6c)
![image](https://github.com/user-attachments/assets/24aca025-f655-44f3-9435-e5e645a74270)

Glad to see it's been trending in a good direction.

**Comment by MikeH1999** [comment] 2024-07-25 07:48
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-25 07:54
great

**Comment by MikeH1999** [comment] 2024-07-26 01:10
allocated 50TiB+512TiB+1024TiB+1024TiB+1024TiB+1024TiB=4562TiB

**Comment by MikeH1999** [comment] 2024-07-26 04:02
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-07-26 04:24
Number of replicas to store ：5

You can explain that the number of copies was 5 when you filled it out, but now it's 11 copies, and the larger storage is 7 copies

**Comment by Hunter3576** [comment] 2024-07-26 04:28
> Number of replicas to store ：5
> 
> You can explain that the number of copies was 5 when you filled it out, but now it's 11 copies, and the larger storage is 7 copies

Due to the incident with the STFIL team, it caused my plan to be disrupted and I had to look for new customers, however, there is still stfil related SP information left in the report, which has actually terminated all the sectors, so it resulted in a copy number of 11. The new customers have varying sizes of data, which may have resulted in a misjudgment of the copies when distributing the data, I'll pay attention to it here，We'll improve on that next time.

**Comment by MikeH1999** [comment] 2024-07-26 04:29
I'll keep an eye on the data distribution

**Comment by MikeH1999** [comment] 2024-07-26 04:30
Retrieval rates are up overall. Fantastic.
![image](https://github.com/user-attachments/assets/e707ae34-ca24-4c0a-8683-49cfa1a8e3bf)
![image](https://github.com/user-attachments/assets/00e30eaa-42a2-4df9-9c62-bfb97e008db1)

**Comment by MikeH1999** [comment] 2024-07-29 03:58
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-08-04 06:57
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-08-09 02:33
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-08-19 09:11
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-09-05 01:40
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-09-18 06:35
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-09-18 06:39
Affected by the STFIL incident, resulting in confusing data reports, close this issue, Re-applicable, thank you!

**Closed by MikeH1999** 2024-09-18 06:39 UTC
Labels: Refill needed

**Comment by MikeH1999** [comment] 2024-09-24 02:11
checker:manualTrigger

**Comment by MikeH1999** [comment] 2024-09-24 02:13
Looks like it's a bug.
https://github.com/fidlabs/allocator-tooling/issues/73
